import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { imageUrl } from './api';
import { EmptyState, ErrorBanner, LoadingState, money, PrimaryButton, ProductCard, SectionTitle, SizeSheet } from './components';
import { showError, useStore } from './store';
import { colors, shadow } from './theme';
import type { Delivery, Product } from './types';

function Catalogue({ items }: { items: Product[] }) {
  const router = useRouter();
  const { favourites, toggleFavourite, addToCart, user } = useStore();
  const [quickProduct, setQuickProduct] = useState<Product | null>(null);
  return <><View style={styles.grid}>{items.map(product => <ProductCard key={product.id} product={product} saved={favourites.includes(product.id)} onOpen={() => router.push(`/product/${product.id}`)} onQuickAdd={() => setQuickProduct(product)} onFavourite={async () => { if (!user) { router.push('/signin'); return; } try { await toggleFavourite(product.id); } catch (e) { showError(e); } }} />)}</View><SizeSheet product={quickProduct} visible={Boolean(quickProduct)} onClose={() => setQuickProduct(null)} onSelect={async size => { if (quickProduct) await addToCart(quickProduct, size); }} /></>;
}

export function HomeScreen() {
  const router = useRouter();
  const { products, loading, error, refresh } = useStore();
  if (loading) return <LoadingState />;
  return <ScrollView style={styles.screen} refreshControl={<RefreshControl refreshing={false} onRefresh={refresh} tintColor={colors.blue} />}>
    <ErrorBanner message={error} retry={refresh} />
    <View style={styles.hero}><Image source={{ uri: imageUrl('hero-center.png') }} style={styles.heroImage} /><View style={styles.heroShade} /><View style={styles.heroCopy}><Text style={styles.heroKicker}>NIKKIBEE</Text><Text style={styles.heroTitle}>Where Style Meets Your Story</Text><Text style={styles.heroText}>Timeless pieces, made for every version of you.</Text><PrimaryButton title="Shop Collection" onPress={() => router.push('/shop')} icon="arrow-forward" /></View></View>
    <View style={styles.storyCard}><View style={styles.storyCopy}><Text style={styles.kicker}>NEW COLLECTION</Text><Text style={styles.storyTitle}>Sunrise Collection</Text><Text style={styles.body}>Soft colour, effortless shapes and bold details for every part of your day.</Text><Pressable onPress={() => router.push('/shop')}><Text style={styles.link}>Explore collection  →</Text></Pressable></View><Image source={{ uri: imageUrl('sunrise-one.png') }} style={styles.storyImage} /></View>
    <SectionTitle eyebrow="JUST IN" title="New Arrivals" action={<Pressable onPress={() => router.push('/shop')}><Text style={styles.link}>See all</Text></Pressable>} />
    <Catalogue items={products.slice(0, 4)} />
    <View style={styles.bottomSpace} />
  </ScrollView>;
}

export function ShopScreen() {
  const { products, loading, error, refresh } = useStore();
  const categories = ['All', ...Array.from(new Set(products.map(p => p.category)))];
  const [category, setCategory] = useState('All'); const [query, setQuery] = useState('');
  const items = useMemo(() => products.filter(p => (category === 'All' || p.category === category) && `${p.name} ${p.color}`.toLowerCase().includes(query.toLowerCase())), [products, category, query]);
  if (loading) return <LoadingState />;
  return <ScrollView style={styles.screen} refreshControl={<RefreshControl refreshing={false} onRefresh={refresh} tintColor={colors.blue} />}><ErrorBanner message={error} retry={refresh} /><SectionTitle eyebrow="THE COLLECTION" title="Shop" />
    <View style={styles.search}><Ionicons name="search" size={19} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search pieces" placeholderTextColor={colors.muted} style={styles.searchInput} /></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map(item => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item}</Text></Pressable>)}</ScrollView>
    {items.length ? <Catalogue items={items} /> : <EmptyState icon="search" title="No pieces found" message="Try another search or category." />}<View style={styles.bottomSpace} />
  </ScrollView>;
}

export function ProductScreen() {
  const router = useRouter();
  const { productId } = useLocalSearchParams<{ productId: string }>();
  const { products, favourites, toggleFavourite, addToCart, user } = useStore();
  const product = products.find(item => item.id === productId); const [size, setSize] = useState(''); const [adding, setAdding] = useState(false);
  if (!product) return <EmptyState title="Piece unavailable" message="This item is no longer in the collection." />;
  const add = async () => { if (!size) { Alert.alert('Choose a size', 'Select your size before adding this piece.'); return; } setAdding(true); try { await addToCart(product, size); Alert.alert('Added to your bag', `${product.name}, size ${size}`); } catch (e) { showError(e); } finally { setAdding(false); } };
  return <ScrollView style={styles.screen}><Image source={{ uri: imageUrl(product.image) }} style={styles.detailImage} /><View style={styles.detailBody}><Text style={styles.kicker}>{product.category.toUpperCase()}</Text><Text style={styles.detailTitle}>{product.name}</Text><Text style={styles.detailPrice}>{money(product.price)}</Text><Text style={styles.body}>{product.description}</Text><View style={styles.infoRow}><Text style={styles.infoLabel}>COLOUR</Text><Text style={styles.infoValue}>{product.color}</Text></View><Text style={styles.infoLabel}>SELECT SIZE</Text><View style={styles.detailSizes}>{product.sizes.map(item => <Pressable key={item} onPress={() => setSize(item)} style={[styles.detailSize, size === item && styles.detailSizeActive]}><Text style={[styles.detailSizeText, size === item && styles.detailSizeTextActive]}>{item}</Text></Pressable>)}</View><PrimaryButton title={adding ? 'Adding…' : 'Add to Bag'} disabled={adding || !product.sizes.length} onPress={add} icon="bag-outline" /><Pressable style={styles.saveRow} onPress={async () => { if (!user) router.push('/signin'); else try { await toggleFavourite(product.id); } catch (e) { showError(e); } }}><Ionicons name={favourites.includes(product.id) ? 'heart' : 'heart-outline'} size={21} color={colors.blue} /><Text style={styles.link}>{favourites.includes(product.id) ? 'Saved' : 'Save item'}</Text></Pressable></View></ScrollView>;
}

export function SavedScreen() {
  const { products, favourites, user } = useStore();
  if (!user) return <SignInPrompt title="Keep the pieces you love" message="Sign in to sync favourites across all your devices." />;
  const items = products.filter(p => favourites.includes(p.id));
  return <ScrollView style={styles.screen}><SectionTitle eyebrow="SAVED" title="Favourites" />{items.length ? <Catalogue items={items} /> : <EmptyState icon="heart-outline" title="Nothing saved yet" message="Tap the heart on any piece to keep it here." />}</ScrollView>;
}

export function CartScreen() {
  const router = useRouter();
  const { cart, changeQuantity, removeItem, user } = useStore();
  return <ScrollView style={styles.screen}><SectionTitle eyebrow="YOUR BAG" title={`Bag · ${cart.count}`} />{cart.items.length ? <><View style={styles.listCard}>{cart.items.map((item, index) => <View key={item.id} style={[styles.cartRow, index > 0 && styles.rowBorder]}><Image source={{ uri: imageUrl(item.image) }} style={styles.cartImage} /><View style={styles.cartCopy}><View><Text style={styles.cartName}>{item.name}</Text><Text style={styles.cartMeta}>{item.color} · Size {item.size}</Text></View><Text style={styles.cartPrice}>{money(item.lineTotal)}</Text><View style={styles.cartActions}><View style={styles.stepper}><Pressable onPress={() => changeQuantity(item, item.quantity - 1)}><Ionicons name="remove" size={20} color={colors.blue} /></Pressable><Text style={styles.stepValue}>{item.quantity}</Text><Pressable onPress={() => changeQuantity(item, item.quantity + 1)}><Ionicons name="add" size={20} color={colors.blue} /></Pressable></View><Pressable onPress={() => Alert.alert('Remove item?', `${item.name}, size ${item.size}`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => removeItem(item).catch(showError) }])}><Text style={styles.remove}>Remove</Text></Pressable></View></View></View>)}</View><View style={styles.summary}><Text style={styles.summaryTitle}>Order Summary</Text><View style={styles.summaryLine}><Text style={styles.body}>Subtotal</Text><Text style={styles.summaryTotal}>{money(cart.subtotal)}</Text></View><Text style={styles.pending}>Delivery is calculated after your order request.</Text><PrimaryButton title={user ? 'Continue to Checkout' : 'Sign in to Checkout'} onPress={() => router.push(user ? '/checkout' : '/signin')} /></View></> : <EmptyState title="Your bag is empty" message="Add a piece and it will appear here." />}</ScrollView>;
}

function SignInPrompt({ title, message }: { title: string; message: string }) {
  const router = useRouter();
  return <SafeAreaView style={styles.centerScreen}><View style={styles.signIcon}><Ionicons name="person-outline" size={32} color={colors.blue} /></View><Text style={styles.signTitle}>{title}</Text><Text style={styles.signText}>{message}</Text><View style={styles.fullButton}><PrimaryButton title="Continue with Google" icon="logo-google" onPress={() => router.push('/signin')} /></View></SafeAreaView>;
}

export function AccountScreen() {
  const router = useRouter();
  const { user, orders, signOut } = useStore();
  if (!user) return <SignInPrompt title="Your NikkiBee account" message="Sign in to sync your bag, favourites and orders." />;
  return <ScrollView style={styles.screen}><SectionTitle eyebrow="ACCOUNT" title={`Hello, ${user.name?.split(' ')[0] || 'there'}`} /><View style={styles.profileCard}>{user.image ? <Image source={{ uri: user.image }} style={styles.avatar} /> : <View style={styles.avatarFallback}><Ionicons name="person" size={28} color={colors.blue} /></View>}<View style={{ flex: 1 }}><Text style={styles.profileName}>{user.name}</Text><Text style={styles.profileEmail}>{user.email}</Text></View></View><View style={styles.menuCard}><Pressable style={styles.menuRow} onPress={() => router.push('/orders')}><View style={styles.menuIcon}><Ionicons name="receipt-outline" size={21} color={colors.blue} /></View><View style={{ flex: 1 }}><Text style={styles.menuTitle}>Orders</Text><Text style={styles.menuMeta}>{orders.length ? `${orders.length} order${orders.length === 1 ? '' : 's'}` : 'No orders yet'}</Text></View><Ionicons name="chevron-forward" size={20} color="#AEAEB2" /></Pressable><View style={styles.rowBorder} /><Pressable style={styles.menuRow} onPress={() => router.push('/saved')}><View style={styles.menuIcon}><Ionicons name="heart-outline" size={21} color={colors.blue} /></View><Text style={[styles.menuTitle, { flex: 1 }]}>Saved pieces</Text><Ionicons name="chevron-forward" size={20} color="#AEAEB2" /></Pressable></View><Pressable style={styles.signOut} onPress={() => Alert.alert('Sign out?', 'Your synced bag will be waiting when you return.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign Out', style: 'destructive', onPress: () => signOut().catch(showError) }])}><Text style={styles.signOutText}>Sign Out</Text></Pressable></ScrollView>;
}

export function SignInScreen() {
  const router = useRouter();
  const { signIn } = useStore(); const [busy, setBusy] = useState(false);
  const connect = async () => { setBusy(true); try { await signIn(); router.replace('/'); } catch (e) { showError(e); } finally { setBusy(false); } };
  return <SafeAreaView style={styles.centerScreen}><View style={styles.signIcon}><Ionicons name="sparkles-outline" size={32} color={colors.blue} /></View><Text style={styles.kicker}>YOUR ACCOUNT</Text><Text style={styles.signTitle}>Sign in to NikkiBee</Text><Text style={styles.signText}>Keep your bag, saved pieces and order history with you across devices.</Text><View style={styles.fullButton}><PrimaryButton title={busy ? 'Connecting…' : 'Continue with Google'} disabled={busy} icon="logo-google" onPress={connect} /></View><Text style={styles.privacy}>We only use your Google profile to create and secure your NikkiBee account.</Text></SafeAreaView>;
}

export function OrdersScreen() {
  const { orders } = useStore();
  return <ScrollView style={styles.screen}><SectionTitle eyebrow="ACCOUNT" title="Orders" />{orders.length ? <View style={styles.listCard}>{orders.map((order, index) => <View key={order.id} style={[styles.orderRow, index > 0 && styles.rowBorder]}><View style={styles.orderHead}><View><Text style={styles.cartName}>Order {order.orderNumber}</Text><Text style={styles.cartMeta}>{new Date(order.createdAt).toLocaleDateString('en-NG', { dateStyle: 'medium' })}</Text></View><Text style={styles.cartPrice}>{money(order.total)}</Text></View><View style={styles.paymentPill}><View style={styles.pendingDot} /><Text style={styles.paymentText}>{order.paymentLabel}</Text></View></View>)}</View> : <EmptyState icon="receipt-outline" title="No orders yet" message="Submitted order requests will appear here." />}</ScrollView>;
}

export function CheckoutScreen() {
  const router = useRouter();
  const { user, cart, placeOrder } = useStore(); const names = user?.name?.split(' ') || [];
  const [form, setForm] = useState<Delivery>({ firstName: names[0] || '', lastName: names.slice(1).join(' '), email: user?.email || '', phone: '', address: '', city: 'Jos', state: 'Plateau State', note: '' }); const [busy, setBusy] = useState(false);
  if (!user) return <SignInPrompt title="Sign in to continue" message="Your account is required before submitting an order." />;
  const field = (key: keyof Delivery, label: string, options: any = {}) => <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><TextInput value={form[key]} onChangeText={value => setForm(current => ({ ...current, [key]: value }))} placeholderTextColor={colors.muted} style={[styles.input, options.multiline && styles.textarea]} {...options} /></View>;
  const submit = async () => { if (!form.firstName || !form.lastName || !form.email || !form.phone || !form.address || !form.city || !form.state) { Alert.alert('Complete your details', 'All delivery fields are required.'); return; } setBusy(true); try { await placeOrder(form); Alert.alert('Order received', 'Payment pending. Your request is not yet confirmed for fulfilment.', [{ text: 'View Orders', onPress: () => router.replace('/orders') }]); } catch (e) { showError(e); } finally { setBusy(false); } };
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.screen}><ScrollView keyboardShouldPersistTaps="handled"><SectionTitle eyebrow="CHECKOUT" title="Delivery Details" /><View style={styles.formCard}>{field('firstName', 'First name')}{field('lastName', 'Last name')}{field('email', 'Email', { keyboardType: 'email-address', autoCapitalize: 'none' })}{field('phone', 'Phone number', { keyboardType: 'phone-pad' })}{field('address', 'Delivery address')}{field('city', 'City')}{field('state', 'State')}{field('note', 'Order note (optional)', { multiline: true })}</View><View style={styles.summary}><View style={styles.summaryLine}><Text style={styles.summaryTitle}>{cart.count} items</Text><Text style={styles.summaryTotal}>{money(cart.subtotal)}</Text></View><View style={styles.paymentNotice}><Ionicons name="time-outline" size={20} color="#9A6700" /><View style={{ flex: 1 }}><Text style={styles.paymentNoticeTitle}>Payment pending</Text><Text style={styles.pending}>Submitting creates an order request. It does not confirm payment or fulfilment.</Text></View></View><PrimaryButton title={busy ? 'Submitting…' : 'Place Order'} disabled={busy} onPress={submit} /></View><View style={styles.bottomSpace} /></ScrollView></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background }, bottomSpace: { height: 30 },
  hero: { height: 610, margin: 16, borderRadius: 30, overflow: 'hidden', backgroundColor: colors.ink, ...shadow }, heroImage: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, width: '100%', height: '100%' }, heroShade: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(4,12,29,.42)' }, heroCopy: { flex: 1, padding: 24, paddingTop: 280, justifyContent: 'flex-end' }, heroKicker: { marginBottom: 8, color: '#D9E4FF', fontSize: 12, fontWeight: '800', letterSpacing: 2 }, heroTitle: { color: 'white', fontSize: 42, lineHeight: 44, fontWeight: '800', letterSpacing: -1.5 }, heroText: { marginVertical: 15, color: 'rgba(255,255,255,.88)', fontSize: 16, lineHeight: 23 },
  storyCard: { minHeight: 240, marginHorizontal: 16, marginTop: 12, borderRadius: 24, overflow: 'hidden', flexDirection: 'row', backgroundColor: colors.card, ...shadow }, storyCopy: { flex: 1.18, padding: 20, justifyContent: 'center' }, storyImage: { width: '40%', height: '100%' }, kicker: { marginBottom: 7, color: colors.blue, fontSize: 12, fontWeight: '800', letterSpacing: 1.3 }, storyTitle: { color: colors.ink, fontSize: 25, lineHeight: 29, fontWeight: '800' }, body: { marginVertical: 12, color: colors.muted, fontSize: 15, lineHeight: 23 }, link: { color: colors.blue, fontSize: 15, fontWeight: '700' },
  grid: { paddingHorizontal: 16, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  search: { minHeight: 48, marginHorizontal: 16, paddingHorizontal: 14, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: '#E3E3E8' }, searchInput: { flex: 1, color: colors.ink, fontSize: 16 }, chips: { paddingHorizontal: 16, paddingVertical: 14, gap: 8 }, chip: { minHeight: 38, paddingHorizontal: 16, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card }, chipActive: { backgroundColor: colors.blue }, chipText: { color: colors.ink, fontSize: 14, fontWeight: '600' }, chipTextActive: { color: 'white' },
  detailImage: { width: '100%', aspectRatio: .78, backgroundColor: colors.pale }, detailBody: { marginTop: -24, padding: 22, paddingTop: 28, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: colors.card }, detailTitle: { color: colors.ink, fontSize: 34, fontWeight: '800', letterSpacing: -1 }, detailPrice: { marginTop: 8, color: colors.ink, fontSize: 22, fontWeight: '700' }, infoRow: { marginTop: 12, marginBottom: 22, flexDirection: 'row', justifyContent: 'space-between' }, infoLabel: { marginBottom: 10, color: colors.muted, fontSize: 12, fontWeight: '700', letterSpacing: 1 }, infoValue: { color: colors.ink, fontSize: 15, fontWeight: '600' }, detailSizes: { marginBottom: 24, flexDirection: 'row', gap: 10 }, detailSize: { width: 52, height: 46, borderWidth: 1, borderColor: colors.separator, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, detailSizeActive: { borderColor: colors.blue, backgroundColor: colors.blue }, detailSizeText: { color: colors.ink, fontSize: 15, fontWeight: '600' }, detailSizeTextActive: { color: 'white' }, saveRow: { minHeight: 48, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  listCard: { marginHorizontal: 16, borderRadius: 20, overflow: 'hidden', backgroundColor: colors.card }, rowBorder: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.separator }, cartRow: { padding: 14, flexDirection: 'row', gap: 14 }, cartImage: { width: 92, height: 120, borderRadius: 13, backgroundColor: colors.pale }, cartCopy: { flex: 1, justifyContent: 'space-between' }, cartName: { color: colors.ink, fontSize: 16, fontWeight: '700' }, cartMeta: { marginTop: 4, color: colors.muted, fontSize: 13 }, cartPrice: { color: colors.ink, fontSize: 16, fontWeight: '700' }, cartActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, stepper: { height: 36, paddingHorizontal: 9, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: colors.background }, stepValue: { minWidth: 16, textAlign: 'center', color: colors.ink, fontWeight: '700' }, remove: { color: colors.danger, fontSize: 13, fontWeight: '600' },
  summary: { margin: 16, padding: 20, borderRadius: 20, gap: 16, backgroundColor: colors.card, ...shadow }, summaryTitle: { color: colors.ink, fontSize: 20, fontWeight: '700' }, summaryLine: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, summaryTotal: { color: colors.ink, fontSize: 21, fontWeight: '800' }, pending: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  centerScreen: { flex: 1, padding: 28, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, signIcon: { width: 68, height: 68, marginBottom: 20, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blueSoft }, signTitle: { color: colors.ink, fontSize: 30, lineHeight: 36, fontWeight: '800', textAlign: 'center', letterSpacing: -.8 }, signText: { maxWidth: 330, marginTop: 12, color: colors.muted, fontSize: 16, lineHeight: 23, textAlign: 'center' }, fullButton: { width: '100%', marginTop: 28 }, privacy: { maxWidth: 320, marginTop: 18, color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  profileCard: { marginHorizontal: 16, padding: 18, borderRadius: 20, flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: colors.card }, avatar: { width: 58, height: 58, borderRadius: 29 }, avatarFallback: { width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blueSoft }, profileName: { color: colors.ink, fontSize: 18, fontWeight: '700' }, profileEmail: { marginTop: 4, color: colors.muted, fontSize: 13 }, menuCard: { margin: 16, borderRadius: 20, overflow: 'hidden', backgroundColor: colors.card }, menuRow: { minHeight: 72, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 13 }, menuIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blueSoft }, menuTitle: { color: colors.ink, fontSize: 16, fontWeight: '600' }, menuMeta: { marginTop: 3, color: colors.muted, fontSize: 12 }, signOut: { minHeight: 50, marginHorizontal: 16, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card }, signOutText: { color: colors.danger, fontSize: 16, fontWeight: '600' },
  orderRow: { padding: 18, gap: 14 }, orderHead: { flexDirection: 'row', justifyContent: 'space-between' }, paymentPill: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#FFF6D8' }, pendingDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#C78500' }, paymentText: { color: '#805600', fontSize: 12, fontWeight: '700' },
  formCard: { marginHorizontal: 16, padding: 18, borderRadius: 20, gap: 16, backgroundColor: colors.card }, field: { gap: 7 }, fieldLabel: { color: colors.ink, fontSize: 13, fontWeight: '600' }, input: { minHeight: 48, paddingHorizontal: 13, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.separator, borderRadius: 12, color: colors.ink, fontSize: 16, backgroundColor: '#FAFAFC' }, textarea: { minHeight: 96, paddingTop: 12, textAlignVertical: 'top' }, paymentNotice: { padding: 14, borderRadius: 14, flexDirection: 'row', gap: 10, backgroundColor: '#FFF9E8' }, paymentNoticeTitle: { marginBottom: 3, color: '#805600', fontSize: 14, fontWeight: '700' },
});
